name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./news/pom.xml
          mvn clean package -f ./board/pom.xml
          mvn clean package -f ./comment/pom.xml
          mvn clean package -f ./detect/pom.xml
          mvn clean package -f ./analyse/pom.xml
          mvn clean package -f ./mypage/pom.xml
          mvn clean package -f ./notify/pom.xml

      - name: Docker Build and push for News
        uses: docker/build-push-action@v4
        with:
          context: ./news
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/news:latest
            ghcr.io/${{ github.repository }}/news:${{ github.ref_name }}
            
      - name: Docker Build and push for Board
        uses: docker/build-push-action@v4
        with:
          context: ./board
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/board:latest
            ghcr.io/${{ github.repository }}/board:${{ github.ref_name }}
            
      - name: Docker Build and push for Comment
        uses: docker/build-push-action@v4
        with:
          context: ./comment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/comment:latest
            ghcr.io/${{ github.repository }}/comment:${{ github.ref_name }}
            
      - name: Docker Build and push for Detect
        uses: docker/build-push-action@v4
        with:
          context: ./detect
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/detect:latest
            ghcr.io/${{ github.repository }}/detect:${{ github.ref_name }}
            
      - name: Docker Build and push for Analyse
        uses: docker/build-push-action@v4
        with:
          context: ./analyse
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/analyse:latest
            ghcr.io/${{ github.repository }}/analyse:${{ github.ref_name }}
            
      - name: Docker Build and push for Mypage
        uses: docker/build-push-action@v4
        with:
          context: ./mypage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypage:latest
            ghcr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
            
      - name: Docker Build and push for Notify
        uses: docker/build-push-action@v4
        with:
          context: ./notify
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notify:latest
            ghcr.io/${{ github.repository }}/notify:${{ github.ref_name }}
            
