server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: news
          uri: http://localhost:8082
          predicates:
            - Path=/news/**, 
        - id: board
          uri: http://localhost:8083
          predicates:
            - Path=/boards/**, 
        - id: comment
          uri: http://localhost:8084
          predicates:
            - Path=/comments/**, 
        - id: detect
          uri: http://localhost:8085
          predicates:
            - Path=/detections/**, 
        - id: analyse
          uri: http://localhost:8086
          predicates:
            - Path=/analyses/**, 
        - id: mypage
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: notify
          uri: http://localhost:8088
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: news
          uri: http://news:8080
          predicates:
            - Path=/news/**, 
        - id: board
          uri: http://board:8080
          predicates:
            - Path=/boards/**, 
        - id: comment
          uri: http://comment:8080
          predicates:
            - Path=/comments/**, 
        - id: detect
          uri: http://detect:8080
          predicates:
            - Path=/detections/**, 
        - id: analyse
          uri: http://analyse:8080
          predicates:
            - Path=/analyses/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
