apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse
  labels:
    app: analyse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyse
  template:
    metadata:
      labels:
        app: analyse
    spec:
      containers:
        - name: analyse
          image: "username/analyse:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
